### ISSUE TITLE
Small composer issue

### ISSUE THREAD

**Issue by arrowdesign** [barryvdh/laravel-stack-middleware#9]
Hoi Barry,

I saw you recently added illuminate/support 5.3 to your httpcache package.
Can you also add this 5.3 support to this package?

Solved the composer 5.3 complains with httpcache with an support alias 5.2.
Runs with no problems at all.

Thanks,
Richard

**Comment by barryvdh** [comment]
Cool, tagged v0.2.4!

**Comment by arrowdesign** [comment]
Thanks, Barry! issue solved.
